VERILOG = ../src/top_altair.v ../src/altair.v ../src/jmp_boot.v \
	  ../src/ram_memory.v ../src/rom_memory.v \
	  ../src/i8080.v ../src/mc6850.v ../src/simpleuart.v \
	  ../src/debounce_pb.v ../src/deposit.v ../src/deposit_next.v \
	  ../src/examine.v ../src/examine_next.v \
	  ../src/reset.v ../src/sense_switch.v \
	  ../src/frequency_divider.v

include ulx3s.mk

