VERILOG = ../src/top/top_altair.v ../src/altair.v ../src/jmp_boot.v \
	  ../src/memory/ram_memory.v ../src/memory/rom_memory.v \
	  ../src/cpu/i8080.v ../src/mc6850.v ../src/sys/simpleuart.v \
	  ../src/debounce_pb.v ../src/deposit.v ../src/deposit_next.v \
	  ../src/examine.v ../src/examine_next.v \
	  ../src/reset.v ../src/sense_switch.v \
	  ../src/frequency_divider.v \
	  ../src/lattice/ecp5pll.sv ../src/sys/hdmi.v ../src/sys/ps2.v \
	  ../src/front_panel.v ../src/memory/img_memory.v ../src/memory/palette_memory.v \
	  ../src/osd/osd.v ../src/osd/spi_osd.v ../src/osd/spi_ram_btn.v \
          ../src/osd/spirw_slave_v.v \

DEVICE=85k

include ulx3s.mk

